### PR TITLE
added prefix in path for directories when used

### PR DESCRIPTION
**Pull request by mihairadulescu**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Thank you for your fast acting on it. =)

When you said prefix on the issue #10 i was expecting this to come before the actual key. Didn't read it correctly. 😝

So my question now is:
* Wouldn't this be `aws` bound? I mean, i understand that this is how `aws` works, but since the naming is not conventional (maybe i'm wrong) shouldn't we use another naming?

**Comment by mihairadulescu** [comment]
hmm i would use the same naming... because this prefix stuff is really used in key search base and not folder structure systems.

**Comment by plribeiro3000** [comment]
Hmmm. So this means it is a prefix of something else that can come after it?

**Comment by mihairadulescu** [comment]
yes let`s say you have this keys
```
/Romania/Sibiu/Strand
/Romania/Bucharest/Pipera
/USA/NewYork/Brooklin 

```
and you want to filter folders that are in romania only, In aws you have to make it like
` connection.directories.get(bucket_name, prefix: '/Romania') `
so prefix come for the path... select all paths that are prefixed by '/Romania' meaning you will have this results
```
/Romania/Sibiu
/Romania/Sibiu/Strand
/Romania/Bucharest/
/Romania/Bucharest/Pipera
```

**Comment by plribeiro3000** [comment]
Ouch. Got it. Thanks for bearing with me on this.
I was just trying to see how `fog-google` acts since it does accept a `prefix` key as well.

Let me just check with someone from @fog/fog-google if they use it in the same way.
I understood what you said and i believe they might be doing exactly the same. Just want to have a 👍 from one of them to be sure

**Comment by icco** [comment]
That's how prefix should work, with all of the api changes in GCS lately, I'm not sure if that's how it still works, but that's the intended interaction in fog-google.

**Comment by plribeiro3000** [comment]
Awesome! Thanks @icco !

**Comment by plribeiro3000** [comment]
Thanks for your contribution @mihairadulescu !

**Comment by mihairadulescu** [comment]
when can we have a build for this? i would love to remove my mokey patching from code! :)

**Comment by plribeiro3000** [comment]
In a bit. =)

**Comment by mihairadulescu** [comment]
COOL! let me know when i can update my gem version!

**Comment by plribeiro3000** [comment]
You should be able to get `fog-local` `0.4.0`. =)

**Comment by mihairadulescu** [comment]
@plribeiro3000 i want to make another pr with tests changed to RSpec.. would that help you guys?

**Comment by plribeiro3000** [comment]
@mihairadulescu Not long ago we were trying to unify all repositories to use the same testing framework (`minitest`) and leave `shindo` behind but i guess this is not the case anymore so go for it if you have spare time to do so. =)

**Pull request merged**
